### PR TITLE
Parametric page name and other changes (v2)

### PR DESCRIPTION
**Pull request by dregad**
This is @splitbrain's original contribution (see PR #72), with merge conflicts resolved and some additional code cleanup and fixes, including French translation.

> * a new `@INPUT@` placeholder can be used to reference the given input in namespace setup. For example you could use something like `{{NEWPAGE>foo:@INPUT@:start}}` to let users create new namespaces inside the `foo` namespace. This makes #70 obsolete
>* a new `?` syntax allows to overwrite config options from the syntax (defaults still come from the config setting) Example: `{{NEWPAGE>foo:bar?nohide}}` overwrites the default `hide` setting.
>* support for strftime placeholders in the namespace config. Allows to  create a daily page for example. Example: `{{NEWPAGE>projekt:notes:%Y-%m-%d}}`
>* New option autopage which hides the input field. Together with the new  date placeholder this allows to create a daily page on a single button click. Example: `{{NEWPAGE>journal:%Y-%m-%d?noautopage}}`
>* This PR includes the changes of #71 

I did that many months ago, and never managed to finalize the testing due to lack of time.

Feedback and testing is welcome.

### CODE REVIEW

**Comment by dregad** [comment]
@Whyglobaleyes 
> version [2024-09-14](https://github.com/dregad/dokuwiki-plugin-addnewpage/releases/tag/2024-09-14). I think that includes the merge above but it still doesn't work

Actually it does not. If it did, this pull request would not be open, it would have a *merged* status. You can also see that in the [network graph](https://github.com/dregad/dokuwiki-plugin-addnewpage/network), which shows that this PR's branch (*pr72*) has not been merged into the *master* branch, the tip of which is release 2024-09-14. 

As explained in the PR's description [above](https://github.com/dregad/dokuwiki-plugin-addnewpage/pull/102#issue-2525929132), the reason I did not merge it, is because I did not have time to properly test this code (as I don't use this functionality myself), and I was hoping to get feedback from the community but that has yet to come

> Do I need to do something else to should use the [7id2fib](https://github.com/dregad/dokuwiki-plugin-addnewpage/commit/71d2f1b5a5578ff832607f728eceb7105ff13f44) commit mentioned above please

The easiest way is to manually install the code from this PR (download it from https://github.com/dregad/dokuwiki-plugin-addnewpage/archive/refs/heads/pr72.zip) instead of using the Extension Manager.

It would be great if you could perform some tests and confirm if everything is working as expected.

**Comment by Whyglobaleyes** [comment]
Dear @dregad, monsieur 
I am not worth'; honestly I'm quite excited to have the attention of a proper programmer and especially one of the team that's done so much - thank you for that. It must be obvious that I don't know the first thing about using github so thanks for explaining. I've tried the PR version and I'm not sure where/ how to report back but here goes my description ...

### attempt 1a - core functionality
  * page code = `{{NEWPAGE}}`
  * input on live page = `deleteme_2024_11`
  * created new page = `deleteme_2024_11` = as expected
  * **UNEXPECTED BEHAVIOUR:** _I think this is new since I installed the PR and didn't happen when I used the last version from the plugin manager_: 
    * PREVIOUSLY the namespace dropdown selection box would actually show only the 3 or 4 namespaces I actually use :: 
    * NOW it shows the `plugins` folder with dozens of subdirectories (perhaps over 100) and doesn't show the final few actual namespaces.
    
### attempt 1b - core functionality
  * page code = `{{NEWPAGE>:}}`
  * input on live page = `deleteme_2024_11`
  * created new page = `deleteme_2024_11` = as expected
  * **AS EXPECTED:** specifying the namespace suppresses the namespace dropdown selection box
  * **UNEXPECTED BEHAVIOUR:** _I think this is new since I installed the PR and didn't happen when I used the last version from the plugin manager_: 
    * I use the addnewpage plugin in the [topbar](https://www.dokuwiki.org/tips:topbar) to create new pages VERY quickly.
    * with the PR72 version the namespace dropdown selection box is shown in the topbar and for some reason I can't see the ROOT namespace (which is where I put the majority of my pages)

### attempt 2
  * page code = `{{NEWPAGE>wiki:}}`
  * input on live page = `deleteme2024_11`
  * created new page = `wiki:input:deleteme2024_11`
  * expected new page = `wiki:deleteme2024_11`

### attempt 3
  * page code = `{{NEWPAGE>wiki:@INPUT@}}`
  * input on live page = `deleteme2024_11a`
  * created new page = `wiki:input:deleteme_2024_11a`
  * expected new page = `wiki:deleteme2024_11a`

### attempt 4
  * page code = `{{NEWPAGE>wiki:@INPUT@_%Y_%m_%d}}`
  * input on live page = `deleteme2024_11b`
  * created new page = `wiki:input_2024_11_09:deleteme_2024_11b`
  * expected new page = `wiki:deleteme2024_11b_2024_11_09`

### attempt 5
  * page code = `{{NEWPAGE>wiki:%Y-%m-%d?autopage}}`
  * the "Add Page" button on the live page isn't clickable 

These 4 attempts had the same behaviour when I omitted the `wiki:` namespace definition.

I'm not sure if that's usable feedback. Please let me know if any other information would be better.
many thanks in advance.

**Comment by dregad** [comment]
@Whyglobaleyes 
I'm glad I could help. So if I understand correctly, everything is working as expected ?

@WetenSchaap @bhartshorn @Chris75forumname @Hirschii @cblte @Fabien4941 @jonathanwgebb  @gnoownow10 @stvoigt
You all mentioned interest in this feature / complained that it didn't work at some point (#72, #98), so it would be great if you guys could also test that this PR fixes the problem for you. Thanks in advance for your feedback.

**Comment by bhartshorn** [comment]
I installed using the Extension Manager by pointing to the zip file for the PR. I'm working on testing now, but I apparently deleted the original config which wasn't working. Give me a bit to restore the syntax I was using and try it out, I'll report back.

**Comment by bhartshorn** [comment]
I did not test extensively, but the strftime and autopage override feature both seem to be functioning. I didn't notice any bugs but will keep an eye out and update you if I notice anything.

**Comment by dregad** [comment]
@bhartshorn many thanks for taking the time to test

**Comment by Whyglobaleyes** [comment]
> @Whyglobaleyes
> I'm glad I could help. So if I understand correctly, everything is working as expected ?

yep exactly1
thank you

**Comment by WetenSchaap** [comment]
Hi, 
Thanks a bunch for working on this!

As other have mentioned, strftime and autopage features work well, I tried a few random variations (also with subnamespaces and stuff), and Dokuwiki did what I expected it to do.

What did *not* work is combining the parametric names with pagetemplates:

```
{{NEWPAGE>@NS:@INPUT#pagetemplates:example1,pagetemplates:example2}}
```

will  use the correct templates, but place the new page in `ns:input`, instead of the current namespace with the given input.

**Comment by dregad** [comment]
Thanks for testing @WetenSchaap 

> What did _not_ work is combining the parametric names with pagetemplates:
> 
> ```
> {{NEWPAGE>@NS:@INPUT#pagetemplates:example1,pagetemplates:example2}}
> ```
> 
> will use the correct templates, but place the new page in `ns:input`, instead of the current namespace with the given input.

Is this the actual, exact markup ? If so can you please try with `@NS@:@INPUT@` ?

**Comment by WetenSchaap** [comment]
Oops, yes, made a typo there. Sorry! Don't know why the @ got lost.

with the correct syntax, everything works as expected.

**Pull request merged**
